# Generated by Django 5.1.3 on 2025-07-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_adoptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=10),
        ),
    ]
